version: '3.8'
volumes:
  postgres:
  pgadmin:
services:
  db:
    container_name: postgres
    image: postgres:13-alpine
    restart: always
    env_file:
      - .env.dev
    volumes:
      - postgres:/var/lib/postgresql/data/
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - 5432:5432

  pgadmin:
    container_name: pgadmin
    image: "dpage/pgadmin4:5.5"
    restart: unless-stopped
    env_file:
      - .env.dev
    volumes:
      - pgadmin:/var/lib/pgadmin
    ports:
      - 5555:80
    depends_on:
      - db
