version: '3.8'

services:
  app:
    container_name: app
    image: web:latest
    command: bash -c "alembic upgrade head && uvicorn main:app --reload --workers 1 --host 0.0.0.0 --port 8080"
    ports:
      - 8080:8080
    environment:
      - ENVIRONMENT=sandbox
      - DATABASE_URL=postgres://prtprymxsmgtqh:515cee1fe82e02ad203f5dfb466876c7f0aa171dd4e33b0030dbdd8886f242cb@ec2-3-226-59-11.compute-1.amazonaws.com:5432/d6efav76o88va2
    restart: always
